{{- if .Values.ingress.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "frontend-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend-chart.labels" . | nindent 4 }}
spec:
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: {{ (index .Values.ingress.tls 0).secretName }}
{{- end }}
