# Default values for frontend-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "ghcr.io/newwave4org/newwave4-frontend"
  pullPolicy: IfNotPresent
  tag: "latest"

# Define imagePullSecrets to allow Kubernetes to pull from the private GitHub Packages registry.
imagePullSecrets:
  - name: ghcr-regcred

# Override chart name if needed.
nameOverride: "newwave4-frontend"
fullnameOverride: "newwave4-frontend"

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: "frontend-sa"

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: new.newwave4.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: frontend-tls-certificate
      hosts:
        - new.newwave4.org

resources:
  limits:
    cpu: 150m
    memory: 156Mi
  requests:
    cpu: 150m
    memory: 156Mi

#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#readinessProbe:
#  httpGet:
#    path: /
#    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector:
  kubernetes.io/hostname: newwave4org-node01

tolerations: []

affinity: {}

# Add a writable volume for nginx cache
volumes:
  - name: nginx-cache
    emptyDir: {}

volumeMounts:
  - name: nginx-cache
    mountPath: /var/cache/nginx
